### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by lengjiye-lz** [romainguy/sample-materials-shop#6]
![image](https://user-images.githubusercontent.com/7865510/90601856-68539280-e22b-11ea-9413-6fe43682897d.png)

AndroidView({ context ->
        LayoutInflater.from(context).inflate(
            R.layout.filament_host, FrameLayout(context), false
        ).apply {
            val (engine) = scenes[product.material]!!
            modelViewer = ModelViewer(engine, this as SurfaceView).also {
                setupModelViewer(it)
            }
        }
    })

com.curiouscreature.compose E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.curiouscreature.compose, PID: 9423
    java.lang.NullPointerException
        at androidx.compose.ui.platform.AndroidViewsHandler.onDescendantInvalidated(AndroidViewsHandler.kt:43)
        at com.huawei.hwaps.HwApsImpl.isNonEmptyFrameCase(HwApsImpl.java:338)
        at android.view.ViewGroup.invalidateChild(ViewGroup.java:6142)
        at android.view.View.invalidateInternal(View.java:17779)
        at android.view.View.invalidate(View.java:17730)
        at android.view.View.setFrame(View.java:22300)
        at android.view.SurfaceView.setFrame(SurfaceView.java:389)
        at android.view.View.layout(View.java:22144)
        at androidx.compose.ui.viewinterop.AndroidViewHolder.onLayout(AndroidViewHolder.kt:105)
        at android.view.View.layout(View.java:22147)
        at android.view.ViewGroup.layout(ViewGroup.java:6493)
        at androidx.compose.ui.node.ViewInteropKt.layoutAccordingTo(ViewInterop.kt:163)
        at androidx.compose.ui.node.ViewInteropKt.access$layoutAccordingTo(Unknown Source:0)
        at androidx.compose.ui.node.ViewInteropKt$toLayoutNode$4$measure$1.invoke(ViewInterop.kt:151)
        at androidx.compose.ui.node.ViewInteropKt$toLayoutNode$4$measure$1.invoke(Unknown Source:3)
        at androidx.compose.ui.MeasureScope$layout$1.placeChildren(MeasureScope.kt:73)
        at androidx.compose.ui.node.LayoutNode$layoutChildren$1.invoke(LayoutNode.kt:879)
        at androidx.compose.ui.node.LayoutNode$layoutChildren$1.invoke(Unknown Source:0)
        at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SnapshotStateObserver.kt:132)
        at androidx.compose.ui.platform.AndroidComposeView.observeLayoutModelReads(AndroidComposeView.kt:448)
        at androidx.compose.ui.node.LayoutNode.layoutChildren$ui_release(LayoutNode.kt:866)
        at androidx.compose.ui.node.InnerPlaceable.place(InnerPlaceable.kt:128)
        at androidx.compose.ui.Placeable$PlacementScope.placeAbsolute(Placeable.kt:176)
        at androidx.compose.ui.node.DelegatingLayoutNodeWrapper$performMeasure$1.placeChildren(DelegatingLayoutNodeWrapper.kt:114)
        at androidx.compose.ui.node.DelegatingLayoutNodeWrapper.place(DelegatingLayoutNodeWrapper.kt:101)
        at androidx.compose.ui.Placeable$PlacementScope.placeAbsolute(Placeable.kt:176)
        at androidx.compose.ui.node.DelegatingLayoutNodeWrapper$performMeasure$1.placeChildren(DelegatingLayoutNodeWrapper.kt:114)
        at androidx.compose.ui.node.DelegatingLayoutNodeWrapper.place(DelegatingLayoutNodeWrapper.kt:101)
        at androidx.compose.ui.Placeable$PlacementScope.placeAbsolute(Placeable.kt:176)
        at androidx.compose.ui.node.OuterMeasurablePlaceable.place(OuterMeasurablePlaceable.kt:114)
        at androidx.compose.ui.Placeable$PlacementScope.placeAbsolute(Placeable.kt:176)
        at androidx.compose.ui.Placeable$PlacementScope.placeAbsolute(Placeable.kt:168)
        at androidx.compose.foundation.layout.StackKt$Stack$1$1$6.invoke(Stack.kt:89)
        at androidx.compose.foundation.layout.StackKt$Stack$1$1$6.invoke(Unknown Source:3)
        at androidx.compose.ui.MeasureScope$layout$1.placeChildren(MeasureScope.kt:73)
        at androidx.compose.ui.node.LayoutNode$layoutChildren$1.invoke(LayoutNode.kt:879)
        at androidx.compose.ui.node.LayoutNode$layoutChildren$1.invoke(Unknown Source:0)
        at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SnapshotStateObserver.kt:132)
        at androidx.compose.ui.platform.AndroidComposeView.observeLayoutModelReads(AndroidComposeView.kt:448)
        at androidx.compose.ui.node.LayoutNode.layoutChildren$ui_release(LayoutNode.kt:866)
        at androidx.compose.ui.node.InnerPlaceable.place(InnerPlaceable.kt:128)
        at androidx.compose.ui.Placeable$PlacementScope.placeAbsolute(Placeable.kt:176)
        at androidx.compose.ui.node.DelegatingLayoutNodeWrapper$performMeasure$1.placeChildren(DelegatingLayoutNodeWrapper.kt:114)
        at androidx.compose.ui.node.DelegatingLayoutNodeWrapper.place(DelegatingLayoutNodeWrapper.kt:101)
        at androidx.compose.ui.Placeable$PlacementScope.placeAbsolute(Placeable.kt:176)
        at androidx.compose.ui.node.DelegatingLayoutNodeWrapper$performMeasure$1.placeChildren(DelegatingLayoutNodeWrapper.kt:114)
2020-08-19 14:48:40.978 9423-9423/com.curiouscreature.compose E/AndroidRuntime:     at androidx.compose.ui.node.DelegatingLayoutNodeWrapper.place(DelegatingLayoutNodeWrapper.kt:101)
        at androidx.compose.ui.Placeable$PlacementScope.placeAbsolute(Placeable.kt:176)
        at androidx.compose.ui.node.DelegatingLayoutNodeWrapper$performMeasure$1.placeChildren(DelegatingLayoutNodeWrapper.kt:114)
        at androidx.compose.ui.node.DelegatingLayoutNodeWrapper.place(DelegatingLayoutNodeWrapper.kt:101)
        at androidx.compose.ui.Placeable$PlacementScope.placeAbsolute(Placeable.kt:176)
        at androidx.compose.ui.node.DelegatingLayoutNodeWrapper$performMeasure$1.placeChildren(DelegatingLayoutNodeWrapper.kt:114)
        at androidx.compose.ui.node.DelegatingLayoutNodeWrapper.place(DelegatingLayoutNodeWrapper.kt:101)
        at androidx.compose.ui.Placeable$PlacementScope.placeAbsolute(Placeable.kt:176)
        at androidx.compose.ui.node.OuterMeasurablePlaceable.place(OuterMeasurablePlaceable.kt:114)
        at androidx.compose.ui.Placeable$PlacementScope.placeAbsolute(Placeable.kt:176)
        at androidx.compose.ui.Placeable$PlacementScope.placeAbsolute(Placeable.kt:168)
        at androidx.compose.foundation.layout.RowColumnImplKt$rowColumnMeasureBlocks$1$4.invoke(RowColumnImpl.kt:238)
        at androidx.compose.foundation.layout.RowColumnImplKt$rowColumnMeasureBlocks$1$4.invoke(Unknown Source:3)
        at androidx.compose.ui.MeasureScope$layout$1.placeChildren(MeasureScope.kt:73)
        at androidx.compose.ui.node.LayoutNode$layoutChildren$1.invoke(LayoutNode.kt:879)
        at androidx.compose.ui.node.LayoutNode$layoutChildren$1.invoke(Unknown Source:0)
        at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SnapshotStateObserver.kt:132)
        at androidx.compose.ui.platform.AndroidComposeView.observeLayoutModelReads(AndroidComposeView.kt:448)
        at androidx.compose.ui.node.LayoutNode.layoutChildren$ui_release(LayoutNode.kt:866)
        at androidx.compose.ui.node.InnerPlaceable.place(InnerPlaceable.kt:128)
        at androidx.compose.ui.Placeable$PlacementScope.placeAbsolute(Placeable.kt:176)
        at androidx.compose.ui.node.OuterMeasurablePlaceable.place(OuterMeasurablePlaceable.kt:114)
        at androidx.compose.ui.Placeable$PlacementScope.placeAbsolute(Placeable.kt:176)
        at androidx.compose.ui.Placeable$PlacementScope.placeAbsolute(Placeable.kt:168)
        at androidx.compose.material.SurfaceKt$SurfaceLayout$1$1$2.invoke(Surface.kt:134)
        at androidx.compose.material.SurfaceKt$SurfaceLayout$1$1$2.invoke(Unknown Source:3)
        at androidx.compose.ui.MeasureScope$layout$1.placeChildren(MeasureScope.kt:73)
        at androidx.compose.ui.node.LayoutNode$layoutChildren$1.invoke(LayoutNode.kt:879)
        at androidx.compose.ui.node.LayoutNode$layoutChildren$1.invoke(Unknown Source:0)
        at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SnapshotStateObserver.kt:132)
        at androidx.compose.ui.platform.AndroidComposeView.observeLayoutModelReads(AndroidComposeView.kt:448)
        at androidx.compose.ui.node.LayoutNode.layoutChildren$ui_release(LayoutNode.kt:866)
        at androidx.compose.ui.node.InnerPlaceable.place(InnerPlaceable.kt:128)
        at androidx.compose.ui.Placeable$PlacementScope.placeAbsolute(Placeable.kt:176)
        at androidx.compose.ui.node.DelegatingLayoutNodeWrapper$performMeasure$1.placeChildren(DelegatingLayoutNodeWrapper.kt:114)
        at androidx.compose.ui.node.DelegatingLayoutNodeWrapper.place(DelegatingLayoutNodeWrapper.kt:101)
        at androidx.compose.ui.node.LayerWrapper.place(LayerWrapper.kt:76)
        at androidx.compose.ui.Placeable$PlacementScope.placeAbsolute(Placeable.kt:176)
        at androidx.compose.ui.node.DelegatingLayoutNodeWrapper$performMeasure$1.placeChildren(DelegatingLayoutNodeWrapper.kt:114)
        at androidx.compose.ui.node.DelegatingLayoutNodeWrapper.place(DelegatingLayoutNodeWrapper.kt:101)
        at androidx.compose.ui.Placeable$PlacementScope.placeAbsolute(Placeable.kt:176)
        at androidx.compose.ui.node.DelegatingLayoutNodeWrapper$performMeasure$1.placeChildren(DelegatingLayoutNodeWrapper.kt:114)
        at androidx.compose.ui.node.DelegatingLayoutNodeWrapper.place(DelegatingLayoutNodeWrapper.kt:101)
2020-08-19 14:48:40.979 9423-9423/com.curiouscreature.compose E/AndroidRuntime:     at androidx.compose.ui.node.LayerWrapper.place(LayerWrapper.kt:76)
        at androidx.compose.ui.Placeable$PlacementScope.placeAbsolute(Placeable.kt:176)
        at androidx.compose.ui.Placeable$PlacementScope.placeAutoMirrored(Placeable.kt:180)
        at androidx.compose.ui.Placeable$PlacementScope.place(Placeable.kt:154)
        at androidx.compose.foundation.layout.PaddingModifier$measure$1.invoke(LayoutPadding.kt:175)
        at androidx.compose.foundation.layout.PaddingModifier$measure$1.invoke(Unknown Source:3)
        at androidx.compose.ui.MeasureScope$layout$1.placeChildren(MeasureScope.kt:73)
        at androidx.compose.ui.node.DelegatingLayoutNodeWrapper.place(DelegatingLayoutNodeWrapper.kt:101)
        at androidx.compose.ui.Placeable$PlacementScope.placeAbsolute(Placeable.kt:176)
        at androidx.compose.ui.node.OuterMeasurablePlaceable.place(OuterMeasurablePlaceable.kt:114)
        at androidx.compose.ui.Placeable$PlacementScope.placeAbsolute(Placeable.kt:176)
        at androidx.compose.ui.Placeable$PlacementScope.placeAbsolute(Placeable.kt:168)
        at androidx.compose.foundation.lazy.LazyForState$measure$1$2.invoke(LazyForState.kt:364)
        at androidx.compose.foundation.lazy.LazyForState$measure$1$2.invoke(Unknown Source:3)
        at androidx.compose.ui.MeasureScope$layout$1.placeChildren(MeasureScope.kt:73)
        at androidx.compose.ui.layout.SubcomposeLayoutState$createMeasureBlocks$1$measure$1.placeChildren(SubcomposeLayout.kt:228)
        at androidx.compose.ui.node.LayoutNode$layoutChildren$1.invoke(LayoutNode.kt:879)
        at androidx.compose.ui.node.LayoutNode$layoutChildren$1.invoke(Unknown Source:0)
        at androidx.compose.runtime.snapshots.Snapshot$Companion.observe(Snapshot.kt:1668)
        at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SnapshotStateObserver.kt:127)
        at androidx.compose.ui.platform.AndroidComposeView.observeLayoutModelReads(AndroidComposeView.kt:448)
        at androidx.compose.ui.node.LayoutNode.layoutChildren$ui_release(LayoutNode.kt:866)
        at androidx.compose.ui.node.InnerPlaceable.place(InnerPlaceable.kt:128)
        at androidx.compose.ui.Placeable$PlacementScope.placeAbsolute(Placeable.kt:176)
        at androidx.compose.ui.Placeable$PlacementScope.placeAutoMirrored(Placeable.kt:180)
        at androidx.compose.ui.Placeable$PlacementScope.place(Placeable.kt:154)
        at androidx.compose.foundation.layout.PaddingModifier$measure$1.invoke(LayoutPadding.kt:175)
        at androidx.compose.foundation.layout.PaddingModifier$measure$1.invoke(Unknown Source:3)
        at androidx.compose.ui.MeasureScope$layout$1.placeChildren(MeasureScope.kt:73)
        at androidx.compose.ui.node.DelegatingLayoutNodeWrapper.place(DelegatingLayoutNodeWrapper.kt:101)
        at androidx.compose.ui.Placeable$PlacementScope.placeAbsolute(Placeable.kt:176)
        at androidx.compose.ui.node.DelegatingLayoutNodeWrapper$performMeasure$1.placeChildren(DelegatingLayoutNodeWrapper.kt:114)
        at androidx.compose.ui.node.DelegatingLayoutNodeWrapper.place(DelegatingLayoutNodeWrapper.kt:101)
        at androidx.compose.ui.node.LayerWrapper.place(LayerWrapper.kt:76)
        at androidx.compose.ui.Placeable$PlacementScope.placeAbsolute(Placeable.kt:176)
        at androidx.compose.ui.node.DelegatingLayoutNodeWrapper$performMeasure$1.placeChildren(DelegatingLayoutNodeWrapper.kt:114)
        at androidx.compose.ui.node.DelegatingLayoutNodeWrapper.place(DelegatingLayoutNodeWrapper.kt:101)
        at androidx.compose.ui.Placeable$PlacementScope.placeAbsolute(Placeable.kt:176)
        at androidx.compose.ui.node.DelegatingLayoutNodeWrapper$performMeasure$1.placeChildren(DelegatingLayoutNodeWrapper.kt:114)
        at androidx.compose.ui.node.DelegatingLayoutNodeWrapper.place(DelegatingLayoutNodeWrapper.kt:101)
        at androidx.compose.ui.Placeable$PlacementScope.placeAbsolute(Placeable.kt:176)
        at androidx.compose.ui.node.DelegatingLayoutNodeWrapper$performMeasure$1.placeChildren(DelegatingLayoutNodeWrapper.kt:114)
        at androidx.compose.ui.node.DelegatingLayoutNodeWrapper.place(DelegatingLayoutNodeWrapper.kt:101)
        at androidx.compose.ui.Placeable$PlacementScope.placeAbsolute(Placeable.kt:176)
2020-08-19 14:48:40.979 9423-9423/com.curiouscreature.compose E/AndroidRuntime:     at androidx.compose.ui.Placeable$PlacementScope.placeAutoMirrored(Placeable.kt:180)
        at androidx.compose.ui.Placeable$PlacementScope.place(Placeable.kt:154)
        at androidx.compose.foundation.layout.PaddingModifier$measure$1.invoke(LayoutPadding.kt:175)
        at androidx.compose.foundation.layout.PaddingModifier$measure$1.invoke(Unknown Source:3)
        at androidx.compose.ui.MeasureScope$layout$1.placeChildren(MeasureScope.kt:73)
        at androidx.compose.ui.node.DelegatingLayoutNodeWrapper.place(DelegatingLayoutNodeWrapper.kt:101)
        at androidx.compose.ui.Placeable$PlacementScope.placeAbsolute(Placeable.kt:176)
        at androidx.compose.ui.node.OuterMeasurablePlaceable.place(OuterMeasurablePlaceable.kt:114)
        at androidx.compose.ui.node.OuterMeasurablePlaceable.replace(OuterMeasurablePlaceable.kt:122)
        at androidx.compose.ui.node.LayoutNode.replace$ui_release(LayoutNode.kt:798)
        at androidx.compose.ui.node.MeasureAndLayoutDelegate.measureAndLayout(MeasureAndLayoutDelegate.kt:214)
        at androidx.compose.ui.platform.AndroidComposeView.measureAndLayout(AndroidComposeView.kt:367)
        at androidx.compose.ui.platform.AndroidComposeView.dispatchDraw(AndroidComposeView.kt:492)
        at android.view.View.draw(View.java:21654)
        at android.view.View.updateDisplayListIfDirty(View.java:20511)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4586)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4559)
        at android.view.View.updateDisplayListIfDirty(View.java:20469)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4586)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4559)
        at android.view.View.updateDisplayListIfDirty(View.java:20469)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4586)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4559)
        at android.view.View.updateDisplayListIfDirty(View.java:20469)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4586)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4559)
        at android.view.View.updateDisplayListIfDirty(View.java:20469)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4586)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4559)
        at android.view.View.updateDisplayListIfDirty(View.java:20469)
        at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:584)
        at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:590)
        at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:668)
        at android.view.ViewRootImpl.draw(ViewRootImpl.java:3895)
        at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3703)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2992)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1879)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8170)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1057)
        at android.view.Choreographer.doCallbacks(Choreographer.java:875)
        at android.view.Choreographer.doFrame(Choreographer.java:776)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1042)
        at android.os.Handler.handleCallback(Handler.java:900)
        at android.os.Handler.dispatchMessage(Handler.java:103)
        at android.os.Looper.loop(Looper.java:219)
        at android.app.ActivityThread.main(ActivityThread.java:8347)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1055)

**Comment by romainguy** [comment]
This looks like a device or Compose specific issue, not an app bug.
